//! Build-time crate that compiles the team risk guest ELF and exports IMAGE_ID.
//!
//! The `include!` macro pulls in constants generated by `risc0-build`
//! during the build step. The key exports are `TEAM_RISK_ZKVM_GUEST_ELF` (the
//! compiled RISC-V binary) and `TEAM_RISK_ZKVM_GUEST_ID` (the image ID used
//! for proof verification). Names are derived from the guest package name
//! `team-risk-zkvm-guest`.

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
